/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Space as PrismaSpace,
  Booking as PrismaBooking,
  Review as PrismaReview,
} from "@prisma/client";

export class SpaceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SpaceCountArgs, "select">): Promise<number> {
    return this.prisma.space.count(args);
  }

  async spaces(args: Prisma.SpaceFindManyArgs): Promise<PrismaSpace[]> {
    return this.prisma.space.findMany(args);
  }
  async space(args: Prisma.SpaceFindUniqueArgs): Promise<PrismaSpace | null> {
    return this.prisma.space.findUnique(args);
  }
  async createSpace(args: Prisma.SpaceCreateArgs): Promise<PrismaSpace> {
    return this.prisma.space.create(args);
  }
  async updateSpace(args: Prisma.SpaceUpdateArgs): Promise<PrismaSpace> {
    return this.prisma.space.update(args);
  }
  async deleteSpace(args: Prisma.SpaceDeleteArgs): Promise<PrismaSpace> {
    return this.prisma.space.delete(args);
  }

  async findBookings(
    parentId: string,
    args: Prisma.BookingFindManyArgs
  ): Promise<PrismaBooking[]> {
    return this.prisma.space
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .bookings(args);
  }

  async findReviews(
    parentId: string,
    args: Prisma.ReviewFindManyArgs
  ): Promise<PrismaReview[]> {
    return this.prisma.space
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .reviews(args);
  }
}
