/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingUpdateManyWithoutSpacesInput } from "./BookingUpdateManyWithoutSpacesInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsString,
  MaxLength,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { ReviewUpdateManyWithoutSpacesInput } from "./ReviewUpdateManyWithoutSpacesInput";

@InputType()
class SpaceUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BookingUpdateManyWithoutSpacesInput,
  })
  @ValidateNested()
  @Type(() => BookingUpdateManyWithoutSpacesInput)
  @IsOptional()
  @Field(() => BookingUpdateManyWithoutSpacesInput, {
    nullable: true,
  })
  bookings?: BookingUpdateManyWithoutSpacesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  capacity?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  hourlyRate?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutSpacesInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutSpacesInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutSpacesInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutSpacesInput;
}

export { SpaceUpdateInput as SpaceUpdateInput };
